sudo: required
services:
    - docker
  
before_install:
    - docker build -t michaelseeburger/react_test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true michaelseeburger/react-test npm test -- --coverage

after_success:
  - docker build -t michaelseeburger/multi-client ./client
  - docker build -t michaelseeburger/multi-nginx ./nginx
  - docker build -t michaelseeburger/multi-server ./server
  - docker build -t michaelseeburger/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push -t michaelseeburger/multi-client
  - docker push -t michaelseeburger/multi-nginx
  - docker push -t michaelseeburger/multi-server
  - docker push -t michaelseeburger/multi-worker


